version:            '2'

services:
  web:
    build:          .
    command:        bash -c "sleep infinity"
    environment:
      APP_SETTINGS: "wts.config.DevelopmentConfig"
    volumes:
      - ~/.ipython:/root/.ipython
      - .:/wts


  # web:
  #   build:        .
  #   volumes:
  #     - ~/.ipython:/root/.ipython
  #     - .:/wts
  #   command:      flask run -h 0.0.0.0 -p 80
  #   environment:
  #     APP_SETTINGS: "wts.config.DevelopmentConfig"
  #     FLASK_ENV:  development
  #   ports:
  #     - "5001:80"

  # flask:
  #   build:        .
  #   volumes:
  #     - ~/.ipython:/root/.ipython
  #     - .:/wts
  #   command:      celery -A wts flower --port=80
  #   ports:
  #     - "8090:80"
  #   depends_on:
  #     - worker

  # worker:
  #   build:        .
  #   command:      celery -A wts worker -l info
  #   volumes:
  #     - ~/.ipython:/root/.ipython
  #     - .:/wts
  #   environment:
  #     APP_SETTINGS: "wts.config.DevelopmentConfig"
  #   depends_on:
  #     - rabbit

  # db:
  #   image:        postgres
  #   environment:
  #     POSTGRES_PASSWORD: "wts"
  #     POSTGRES_USER: "wts"
  #     POSTGRES_DB: "wts"
  #     PGDATA:     "/var/lib/postgresql/data/db/"
  #     TZ:         "Europe/Kiev"
  #   volumes:
  #     - db:/var/lib/postgresql/data

  hub:
    image:          nkovacs/selenium-standalone-phantomjs
    volumes:
      - .:/wts
    ports:
      - "4444:4444"

  # rabbit:
  #   image:        rabbitmq:management
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=admin
  #     - RABBITMQ_DEFAULT_PASS=admin
  #     - TZ=Europe/Kiev
  #   ports:
  #     - "4:15672"

# volumes:
#   db:
