"""empty message

Revision ID: 1d0d15d463a9
Revises: c4aa45743b16
Create Date: 2018-12-10 14:47:49.079916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d0d15d463a9'
down_revision = 'c4aa45743b16'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_test_cases():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('func', sa.PickleType(), nullable=True))
    # ### end Alembic commands ###


def downgrade_test_cases():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'func')
    # ### end Alembic commands ###

