"""empty message

Revision ID: 361bbf7733e8
Revises: 8b509bc0ce99
Create Date: 2018-12-04 09:58:56.453746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '361bbf7733e8'
down_revision = '8b509bc0ce99'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes_properties',
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('class_id', 'property_id')
    )
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('classes_properties')
    # ### end Alembic commands ###


def upgrade_test_cases():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_test_cases():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

